services:
  app:
    image: 'canopus-delivery:0.0.1'
    container_name: canopus-delivery
    build: '.'
    ports:
      - "8084:8080"
      - "5005:5005"
    volumes:
      - ~/content:/var/lib/content
    networks:
      - canopus

networks:
  canopus:
    name: canopus