spring:
  application:
    name: canopus-delivery

eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://canopus-discovery:8761/eureka
server:
  port: 8080
logging:
  level:
    root: info
