spring:
  application:
    name: canopus-delivery

  kafka:
    bootstrap-servers: canopus-kafka:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size:
eureka:
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://canopus-discovery:8761/eureka
server:
  port: 8080
logging:
  level:
    root: info
